# 2.5 iRule 우회. native RegularExpression 미적용.
# HTTPRoute 는 두 Pool 을 VS 에 붙이기만 하고, 분기는 iRule regexp + pool.
# TMM pool 이름: web-pool-<Pool.name>-pool (로그 object name)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-gw
  namespace: web
spec:
  gatewayClassName: f5-bnk-gateway-class
  addresses:
    - type: IPAddress
      value: 40.30.20.20
  listeners:
    - name: bnk-listener
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: path-regex-irule-route
  namespace: web
spec:
  parentRefs:
    - name: http-gw
      sectionName: bnk-listener
  hostnames:
    - coffee.f5bnk.com
  rules:
    - backendRefs:
        - name: coffee-pool
          kind: Pool
          group: k8s.f5net.com
          weight: 1
        - name: tea-pool
          kind: Pool
          group: k8s.f5net.com
          weight: 1
---
apiVersion: k8s.f5net.com/v1
kind: Pool
metadata:
  name: coffee-pool
  namespace: web
spec:
  members:
    - address: "30.0.0.10"
      port: 80
---
apiVersion: k8s.f5net.com/v1
kind: Pool
metadata:
  name: tea-pool
  namespace: web
spec:
  members:
    - address: "30.0.0.11"
      port: 80
---
apiVersion: k8s.f5net.com/v1
kind: F5BigCneIrule
metadata:
  name: irule-path-regex
  namespace: web
spec:
  iRule: |
    when HTTP_REQUEST {
      if { [regexp {^/login/[0-9]+$} [HTTP::path]] } {
        pool web-pool-coffee-pool-pool
      } else {
        pool web-pool-tea-pool-pool
      }
    }
---
apiVersion: gateway.k8s.f5net.com/v1alpha1
kind: BNKNetPolicy
metadata:
  name: netpolicy-path-regex
  namespace: web
spec:
  extensionRefs:
    - kind: F5BigCneIrule
      name: irule-path-regex
      group: k8s.f5net.com
  targetRefs:
    - kind: Gateway
      name: http-gw
      group: gateway.networking.k8s.io
      sectionName: bnk-listener
