server {
    listen 30.0.0.12:80;
    server_name _;
    access_log /var/log/nginx/poc-access.log;

    # 2.31 ExternalAuth HTTP path /auth
    location = /auth {
        default_type text/plain;
        return 200 "AUTH OK\n";
    }

    location = /auth/deny {
        default_type text/plain;
        return 401 "AUTH DENY\n";
    }

    location / {
        default_type text/plain;
        add_header X-Echo-Host $http_host always;
        add_header X-Echo-Uri $request_uri always;
        add_header X-Echo-Env $http_env always;
        return 200 "HTTPBIN CANARY SERVER - 30.0.0.12\n";
    }
}
