server {
    listen 30.0.0.10:80;
    server_name _;
    access_log /var/log/nginx/poc-access.log;

    # 2.36 / 2.37 timeout. printf 'COFFEE SERVER - 30.0.0.10\n' > /etc/nginx/poc-slow.txt
    location = /slow {
        default_type text/plain;
        limit_rate 3;
        alias /etc/nginx/poc-slow.txt;
    }

    # 2.38 / 2.39 / 2.40 retry
    location = /fail {
        default_type text/plain;
        return 503 "COFFEE FAIL - 30.0.0.10\n";
    }

    location / {
        default_type text/plain;
        add_header X-Echo-Host $http_host always;
        add_header X-Echo-Uri $request_uri always;
        add_header X-Echo-Method $request_method always;
        add_header X-Echo-X-PoC-Add $http_x_poc_add always;
        add_header X-Echo-X-PoC-Set $http_x_poc_set always;
        add_header X-Echo-X-Remove-Me $http_x_remove_me always;
        add_header X-Echo-X-Backend $http_x_backend always;
        add_header X-Echo-Env $http_env always;
        add_header X-Request-Id $request_id always;
        return 200 "COFFEE SERVER - 30.0.0.10\n";
    }
}
