server {
    listen 30.0.0.11:80;
    server_name _;
    access_log /var/log/nginx/poc-access.log;

    location / {
        default_type text/plain;
        add_header X-Echo-Host $http_host always;
        add_header X-Echo-Uri $request_uri always;
        add_header X-Echo-Method $request_method always;
        add_header X-Echo-Env $http_env always;
        return 200 "TEA SERVER - 30.0.0.11\n";
    }
}
