# Gateway API TCPRoute kind 미지원. BNK native: protocol TCP + L4Route
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp-gw
  namespace: web
spec:
  gatewayClassName: f5-bnk-gateway-class

  addresses:
    - type: IPAddress
      value: 40.30.20.20

  listeners:
    - name: bnk-listener
      protocol: TCP
      port: 22

      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: L4Route
            group: gateway.k8s.f5net.com

---
apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: tcp-listener-80
  namespace: web
spec:
  protocol: TCP
  parentRefs:
    - name: tcp-gw
      sectionName: bnk-listener

  rules:
    - backendRefs:
        - name: coffee-pool
          kind: Pool
          group: k8s.f5net.com
          weight: 1
        - name: tea-pool
          kind: Pool
          group: k8s.f5net.com
          weight: 1

---
apiVersion: k8s.f5net.com/v1
kind: Pool
metadata:
  name: coffee-pool
  namespace: web
spec:
  members:
    - address: "30.0.0.10"
      port: 22
  monitors:
    tcp:
      - interval: 5
        timeout: 16
---
apiVersion: k8s.f5net.com/v1
kind: Pool
metadata:
  name: tea-pool
  namespace: web
spec:
  members:
    - address: "30.0.0.11"
      port: 22
  monitors:
    tcp:
      - interval: 5
        timeout: 16

