apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: udp-gw
  namespace: web
spec:
  gatewayClassName: f5-bnk-gateway-class

  addresses:
    - type: IPAddress
      value: 40.30.20.20

  listeners:
    - name: bnk-listener
      protocol: UDP
      port: 53

      allowedRoutes:
        namespaces:
          from: All

        kinds:
          - kind: UDPRoute

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: udp-listener-route
  namespace: web
spec:
  parentRefs:
    - name: udp-gw
      sectionName: bnk-listener

  rules:
    - backendRefs:
        - name: coffee-pool
          kind: Pool
          group: k8s.f5net.com

---
apiVersion: k8s.f5net.com/v1
kind: Pool
metadata:
  name: coffee-pool
  namespace: web
spec:
  members:
    - address: "30.0.0.10"
      port: 80
