# Gateway API UDPRoute kind 미지원. BNK native: protocol UDP + L4Route
# 백엔드 echo 는 :9053 (호스트 named 가 :53 점유)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: udp-gw
  namespace: web
spec:
  gatewayClassName: f5-bnk-gateway-class

  addresses:
    - type: IPAddress
      value: 40.30.20.20

  listeners:
    - name: bnk-listener
      protocol: UDP
      port: 9053

      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: L4Route
            group: gateway.k8s.f5net.com

---
apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: udp-listener-route
  namespace: web
spec:
  protocol: UDP
  parentRefs:
    - name: udp-gw
      sectionName: bnk-listener

  rules:
    - backendRefs:
        - name: coffee-pool
          kind: Pool
          group: k8s.f5net.com

---
apiVersion: k8s.f5net.com/v1
kind: Pool
metadata:
  name: coffee-pool
  namespace: web
spec:
  members:
    - address: "30.0.0.10"
      port: 9053
